#
# Copyright (c) 2026 Tim Anhalt (BitTim)
#
# Project:    Valolink
# License:    GPLv3
#
# File:       version.properties
# Module:     Valolink.app
# Author:     Tim Anhalt (BitTim)
# Modified:   29.01.26, 15:30
#
BUILD=2094
MAJOR=0
MINOR=1
PATCH=4
