name: "Nightly Snapshot"
on:
  schedule:
    - cron: "0 0 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  # The name of the main module repository
  main_project_module: app

  # The name of the App
  app_name: Valolink

  # The name of the android app package
  package_name: dev.bittim.valolink

jobs:
  CheckNewCommits:
    runs-on: ubuntu-latest
    outputs:
      doRebuild: ${{ steps.decideRebuild.outputs.doRebuild }}

    steps:
      - name: Checking out branch
        uses: actions/checkout@v4

      - name: Get latest commit SHA
        id: latestsha
        run: echo "sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

      - name: Get Previous tag
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"

      - name: Get commit SHA of latest Tag
        id: tagsha
        run: echo "sha=$(git rev-list -n 1 ${{ steps.previoustag.outputs.tag }})" >> $GITHUB_OUTPUT

      - name: Decide rebuild
        id: decideRebuild
        env:
          LATEST_SHA: ${{ steps.latestsha.outputs.sha }}
          TAG_SHA: ${{ steps.tagsha.outputs.sha }}
        run: |
          if [[ $LATEST_SHA == $TAG_SHA ]]; then
            echo "doRebuild=false" >> $GITHUB_OUTPUT
          else
            echo "doRebuild=true" >> $GITHUB_OUTPUT
          fi

  GetChanges:
    needs: [CheckNewCommits]
    if: needs.CheckNewCommits.outputs.doRebuild == 'true'
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.changes.outputs.changes }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # you need full history to collect changes correctly
          fetch-depth: 0

      - name: Get Changes between Tags
        id: changes
        uses: simbo/changes-between-tags-action@v1

      - name: Create whatsnew directory and file
        env:
          CHANGES: ${{ steps.changes.outputs.changes }}
        run: |
          mkdir whatsnew
          echo "$CHANGES" > whatsnew/whatsnew-en-US

  Build:
    needs: [CheckNewCommits, GetChanges]
    if: needs.CheckNewCommits.outputs.doRebuild == 'true'
    runs-on: ubuntu-latest

    steps:
      - name: Checking out branch
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@main
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Making gradlew executable
        run: chmod +x ./gradlew

      # This will decode the google-services.json from base 64 text representation that we have stored in secrets
      # and generates and keystore file and gets stored in main module path
      - name: Decode google-services.json
        env:
          GOOGLE_SERVICES_BASE64: ${{ secrets.GOOGLE_SERVICES_BASE_64 }}
        run: |
          echo $GOOGLE_SERVICES_BASE64 | base64 -di > $main_project_module/google-services.json
        
      # Run Tests Build
      - name: Run gradle test
        run: ./gradlew test

      # This will decode the keystore from base 64 text representation that we have stored in secrets
      # and generates and keystore file and gets stored in /android-app path
      - name: Decode Keystore
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE_64 }}
        run: |
          echo $KEYSTORE_BASE64 | base64 -di > keystore.jks

      - name: Build Release apk
        env:
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: ./gradlew assembleRelease --stacktrace

      - name: Build Release bundle
        env:
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: ./gradlew bundleRelease --stacktrace

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Read all values from version.properties
        uses: BrycensRanch/read-properties-action@latest
        id: versionProperties
        with:
          file: app/version.properties
          all: true

      - name: Get current version name
        id: versionName
        run: echo "versionName=$(echo v${{ steps.versionProperties.outputs.MAJOR }}.${{ steps.versionProperties.outputs.MINOR }}.${{ steps.versionProperties.outputs.PATCH }}-${{ steps.versionProperties.outputs.BUILD }})" >> $GITHUB_OUTPUT
        
      - name: Create tag
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ env.app_name }} Nightly ${{ steps.versionName.outputs.versionName }} (${{ steps.date.outputs.date }})',
              sha: context.sha
            })

      - name: Get release file aab path
        id: releaseAab
        run: echo "aabfile=$(find app/build/outputs/bundle/release/*.aab)" >> $GITHUB_OUTPUT

      - name: Get release file apk path
        id: releaseApk
        run: echo "apkfile=$(find app/build/outputs/apk/release/*.apk)" >> $GITHUB_OUTPUT

      - name: Upload Release Build APK to Artifacts
        uses: actions/upload-artifact@v4
        with:
           name: ${{ env.app_name }} Nightly ${{ steps.date.outputs.date }} APK
           path: ${{ steps.releaseApk.outputs.apkfile }}

      - name: Upload Release Build AAB to Artifacts
        uses: actions/upload-artifact@v4
        with:
           name: ${{ env.app_name }} Nightly ${{ steps.date.outputs.date }} AAB
           path: ${{ steps.releaseAab.outputs.aabfile }}

      - name: Upload artifact to Google Play Internal track
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: ${{ env.package_name }}
          releaseFile: ${{ steps.releaseAab.outputs.aabfile }}
          track: internal
          whatsNewDirectory: /whatsnew
          mappingFile: /app/build/outputs/mapping/release/mapping.txt
